name: "sync with simplifier"
description: "Syncs changed files with simplifier"
inputs:
  project_name:
    description: "The api_endpoint to be pushed to."
    required: false
  simplifier_email:
    description: "email needed to interact with the simplifier API"
    required: true
  simplifier_password:
    description: "password needed to interact with the simplifier API"
    required: true
  directories:
    description: "Directories to sync"
    required: true
runs:
  using: "node12"
  main: dist/index.js
